platform:
  image:
    tag: "3.11.3"
  config:
    existingEnvSecret: ret2shell-platform-env
  blocked:
    content: ""

postgresql:
  auth:
    existingSecret: ret2shell-postgresql-credentials

valkey:
  auth:
    existingSecret: ret2shell-valkey-credentials

nats:
  auth:
    existingSecret: ret2shell-nats-credentials
