{{- if .Values.platform.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ret2shell.platformServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ret2shell.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: platform
  {{- with .Values.platform.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.platform.serviceAccount.automountServiceAccountToken }}
{{- end }}

{{- if and (include "ret2shell.createPlatformClusterRBAC" .) (not .Values.platform.rbac.useClusterAdmin) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ret2shell-service
  labels:
    {{- include "ret2shell.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: platform
rules:
  - apiGroups:
      - ""
      - apps
      - autoscaling
      - batch
      - extensions
      - policy
      - networking.k8s.io
    resources:
      - componentstatuses
      - configmaps
      - daemonsets
      - deployments
      - endpoints
      - events
      - ingresses
      - jobs
      - limitranges
      - namespaces
      - networkpolicies
      - nodes
      - persistentvolumeclaims
      - persistentvolumes
      - pods
      - pods/log
      - pods/portforward
      - replicasets
      - replicationcontrollers
      - resourcequotas
      - services
      - statefulsets
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
{{- end }}

{{- if include "ret2shell.createPlatformClusterRBAC" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ret2shell-service-global
  labels:
    {{- include "ret2shell.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: platform
subjects:
  - kind: ServiceAccount
    name: {{ include "ret2shell.platformServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{- if .Values.platform.rbac.useClusterAdmin }} cluster-admin {{- else }} ret2shell-service {{- end }}
{{- end }}
